In [1]:
import pandas as pd
import numpy as np

In [4]:
def ed(m, n):
 return np.sqrt(np.sum((m - n) ** 2))

In [6]:
ed(np.array([1.90,0.97]),np.array([1.79,1.57]))

0.6100000000000001

In [11]:
ed(np.array([1.90,0.97]),np.array([2.035,1.465]))

0.5130789412946123

In [7]:
ed(np.array([1.76,0.84]),np.array([1.79,1.57]))

0.7306161783043134

In [12]:
ed(np.array([1.76,0.84]),np.array([2.035,1.465]))

0.6828250141873833

In [8]:
ed(np.array([2.32,1.63]),np.array([1.79,1.57]))

0.5333854141237833

In [13]:
ed(np.array([2.32,1.63]),np.array([2.035,1.465]))

0.3293174760015019

In [9]:
ed(np.array([2.31,2.09]),np.array([1.79,1.57]))

0.7353910524340093

In [15]:
ed(np.array([2.31,2.09]),np.array([2.035,1.465]))

0.682825014187383

In [10]:
ed(np.array([1.14,2.11]),np.array([1.79,1.57]))

0.8450443775329198

In [16]:
ed(np.array([1.14,2.11]),np.array([2.035,1.465]))

1.1031998912255205

In [2]:
df1=pd.read_csv('adult_train.csv',header=None)
df2=pd.read_csv('adult_test.csv',header=None)
df3=pd.read_csv('adult_names.txt',sep=':',header=None)

In [14]:
df4=df1.iloc[:,np.where(df1.dtypes=='object')[0]]

In [13]:
np.where(df1.dtypes=='object')[0]

array([ 1,  3,  5,  6,  7,  8,  9, 13, 14], dtype=int64)

In [4]:
df1.rename(columns=df3[0],inplace=True)
df2.rename(columns=df3[0],inplace=True)

In [5]:
df2

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,label
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K.
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K.
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K.
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K.
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16276,39,Private,215419,Bachelors,13,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,36,United-States,<=50K.
16277,64,?,321403,HS-grad,9,Widowed,?,Other-relative,Black,Male,0,0,40,United-States,<=50K.
16278,38,Private,374983,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States,<=50K.
16279,44,Private,83891,Bachelors,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,5455,0,40,United-States,<=50K.
16280,35,Self-emp-inc,182148,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,60,United-States,>50K.

In [6]:
col=df1.dtypes[df1.dtypes=='object'].index
col_label=df1[col].nunique()[df1[col].nunique()==2].index
col_one=df1[col].nunique()[df1[col].nunique()!=2].index

In [7]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in col_label:
    df1[i]=le.fit_transform(df1[i])
    df2[i]=le.fit_transform(df2[i])
data1=df1.join(pd.get_dummies(df1[col_one]))
data2=df2.join(pd.get_dummies(df2[col_one]))

In [8]:
df1

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,label
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,1,2174,0,40,United-States,0
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,1,0,0,13,United-States,0
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,1,0,0,40,United-States,0
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,1,0,0,40,United-States,0
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,0,0,0,40,Cuba,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,0,0,0,38,United-States,0
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,1,0,0,40,United-States,1
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,0,0,0,40,United-States,0
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,1,0,0,20,United-States,0
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,0,15024,0,40,United-States,1

In [9]:
class Data():
    def __init__(self,trainPath=None,testPath=None,columns=None,labelColumn=None,OrdinalColumns={}):
        self.trainpath=trainPath
        self.testPath=testPath
        self.columns=columns
        self.labelColumn=labelColumn
        self.OrdinalColumns=OrdinalColumns 
    def readcsv(self):
        df1=pd.read_csv(self.trainpath,header=None)
        df2=pd.read_csv(self.testPath,header=None)
        df1.rename(columns=self.columns,inplace=True)
        df2.rename(columns=self.columns,inplace=True)
        return df1,df2
    def encoder(self):
        df1,df2=self.readcsv()
        col=df1.dtypes[df1.dtypes=='object'].index
        df1[self.labelColumn]=df1[self.labelColumn].map(self.OrdinalColumns)
        df2[self.labelColumn]=df2[self.labelColumn].map(self.OrdinalColumns)
        col=col.drop('label')
        col_label=df1[col].nunique()[df1[col].nunique()==2].index
        col_one=df1[col].nunique()[df1[col].nunique()!=2].index
        le=LabelEncoder()
        df11=df1.copy()
        df22=df1.copy()
        for i in col_label:
            df11[i]=le.fit_transform(df11[i])
            df22[i]=le.fit_transform(df22[i])
        data_train=df11.join(pd.get_dummies(df11[col_one]))
        data_test=df22.join(pd.get_dummies(df22[col_one]))
        data_train.drop(columns=col_one,inplace=True)
        data_test.drop(columns=col_one,inplace=True)
        y_train=df1[self.labelColumn]
        y_test=df2[self.labelColumn]
        data_test.drop(columns=self.labelColumn,inplace=True)
        data_train.drop(columns=self.labelColumn,inplace=True)
        return data_train,data_test,y_train,y_test

In [10]:
df3=pd.read_csv('adult_names.txt',sep=':',header=None)
a=Data('adult_train.csv','adult_test.csv',df3[0],labelColumn='label',OrdinalColumns={' <=50K':0,' >50K':1})

In [11]:

df1,df2=a.readcsv()

In [12]:
data_train,data_test,y_train,y_test=a.encoder()

In [13]:
data_train.to_csv('data_train.csv')
data_test.to_csv('data_test.csv')

In [14]:

from scipy.spatial import distance
from sklearn.model_selection import train_test_split

data1,data2=train_test_split(data_train)
def EuclideanDistances(A, B):
    BT = B.transpose()
    # vecProd = A * BT
    vecProd = np.dot(A,BT)
    # print(vecProd)
    SqA =  A**2
    # print(SqA)
    sumSqA = np.matrix(np.sum(SqA, axis=1))
    sumSqAEx = np.tile(sumSqA.transpose(), (1, vecProd.shape[1]))
    # print(sumSqAEx)
 
    SqB = B**2
    sumSqB = np.sum(SqB, axis=1)
    sumSqBEx = np.tile(sumSqB, (vecProd.shape[0], 1))    
    SqED = sumSqBEx + sumSqAEx - 2*vecProd
    SqED[SqED<0]=0.0   
    ED = np.sqrt(SqED)
    return ED
d=EuclideanDistances(data1,data2)
dist=np.max(d,axis=1)

far=np.array(sorted(dist)).reshape(24420,1)[int(0.9*len(dist))]
near=np.array(sorted(dist)).reshape(24420,1)[int(0.1*len(dist))]
g=np.sqrt((far**2-near**2)/(2*(np.log(far)**2-np.log(near)**2)))
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
tuned_parameters={'C': list(range(1,3)),'gamma':list(range(1,3))}
score= 'precision'
clf = GridSearchCV(SVC(kernel='rbf'), tuned_parameters, cv=5,
                       scoring='%s_macro' % score)
clf.fit(data_train,y_train)
mean_score=clf.cv_results_['mean_test_score']
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
tuned_parameters={'C': list(range(1,3))}
score= 'precision'
clf = GridSearchCV(SVC(kernel='rbf',gamma=1/g[0]), tuned_parameters, cv=5,
                       scoring='%s_macro' % score)
clf.fit(data_train,y_train)
mean_score=clf.cv_results_['mean_test_score']
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
tuned_parameters={'C': list(range(1,3))}
score= 'precision'
clf = GridSearchCV(SVC(kernel='linear',gamma=1/g[0]), tuned_parameters, cv=5,
                       scoring='%s_macro' % score)
clf.fit(data_train,y_train)
mean_score=clf.cv_results_['mean_test_score']
from sklearn.naive_bayes import GaussianNB, BernoulliNB, MultinomialNB
from sklearn.metrics import precision_score
gnb = GaussianNB()
gnb.fit(data_train,y_train)
precision_score(y_test,gnb.predict(data_test))

c:\Users\tang xiaoqing\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\tang xiaoqing\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\tang xiaoqing\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\tang xiaoqing\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [ ]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score, roc_auc_score

class NaiveBayes:
    def __init__(self):
        self.variable_type = dict()
        self.prior = dict()
        self.X = 0
        self.Y = 0

    def fit(self, X, Y):
        self.X = X
        self.Y = Y

        columns = X.columns
        for item in columns:
            if X[item].dtypes in ['float64' ,'float32']:
                self.variable_type[item] = 'float'
            else:
                self.variable_type[item] = 'object'

        Y = Y.to_frame() #将系列对象转换为DataFrame
        num = Y.groupby(list(Y.columns))[list(Y.columns)[0]].agg('count')
        self.prior = (num / np.sum(num)).to_dict() #{' <=50K': 0.7591904425539756, ' >50K': 0.2408095574460244}

    def predict(self, x, **argv):
        if isinstance(x, pd.Series): #判断一个对象是否是一个已知的类型
            P = dict()
            for Y_form, prior in (self.prior).items():
                Y_index = (self.Y == Y_form).values
                p = prior

                for i, value in enumerate(x): #同时列出数据和数据下标
                    form = list(self.variable_type.values())[i]
                    if form == 'float':
                        temp_mean = np.mean(self.X.iloc[Y_index, i])
                        temp_std = np.std(self.X.iloc[Y_index, i])
                        p = p * (np.exp(-(value - temp_mean) ** 2 / (2 * temp_std ** 2)) / (np.sqrt(2 * np.pi) * temp_std))
                    else:
                        temp_dict = (self.X.iloc[Y_index, :].groupby([self.X.columns[i]])[self.X.columns[i]].agg(
                            'count')).to_dict()
                        p = p * (temp_dict.get(value, 1e-4) / np.sum(list(temp_dict.values())))

                P[Y_form] = p
            for item in P.keys():
                P[item] = P[item] / np.sum(list(P.values()))

            return P

        else:
            P = []
            for Y_form, prior in (self.prior).items():
                Y_index = (self.Y == Y_form).values
                p = prior
                i = 0
                while i < len(self.X.columns):
                    form = list(self.variable_type.values())[i]
                    if form == 'float':
                        tmp_mean = np.mean(self.X.iloc[Y_index, i])
                        tmp_std =  np.std(self.X.iloc[Y_index, i])
                        p = p * (np.exp(-(np.array(x.iloc[:, i]) - tmp_mean) ** 2 / (2 * tmp_std ** 2)) / (
                                np.sqrt(2 * np.pi) * tmp_std))
                        i += 1
                    else:
                        tmp_dict = (self.X.iloc[Y_index, :].groupby([self.X.columns[i]])[self.X.columns[i]].agg(
                            'count')).to_dict()
                        p = p * (np.array(list(map(lambda x: tmp_dict.get(x, 1e-4), np.array(x.iloc[:, i])))) / np.sum(
                            list(tmp_dict.values())))
                        i += 1
                P.append(p)
            return pd.DataFrame(data=(P / np.sum(P, axis=0)).T, columns=(self.prior).keys())

    def score(self, tX, tY, criteria="accuracy"):
        Y_temp = self.predict(tX)
        if isinstance(Y_temp, dict):
            if criteria == "accuracy":
                Y = max(Y_temp, key=Y_temp.get)
                return accuracy_score([tY], [Y])
            else:
                Y = Y_temp[max(Y_temp, key=Y_temp.get)]
                return roc_auc_score([tY], [Y])

        else:
            if criteria == "accuracy":
                Y = np.argmax(np.array(Y_temp), axis=1)
                Y = np.array(Y_temp.columns)[Y]
                return accuracy_score(tY, Y)
            else:
                tY = list(map(lambda x: np.argwhere(np.array(Y_temp.columns) == x)[0,0], tY.values))
                Y = Y_temp.loc[:, Y_temp.columns[1]]
                return roc_auc_score(tY, Y)


if __name__ == '__main__':
    data1 = pd.read_csv('adult_train.csv', header=None)
    Y = data1.iloc[:, -1]
    X = data1.iloc[:, :-1]
    X.iloc[:, [0, 2, 4, 10, 11, 12]] = X.iloc[:, [0, 2, 4, 10, 11, 12]].astype('float64')

    data2 = pd.read_csv('adult_test.csv', header=None)
    y = data2.iloc[:, -1]  #将adult_test.csv最后一列的.删除
    x = data2.iloc[:, :-1]
    x.iloc[:, [0, 2, 4, 10, 11, 12]] = x.iloc[:, [0, 2, 4, 10, 11, 12]].astype('float64')

    answer = NaiveBayes()
    answer.fit(X,Y)
    print(answer.predict(x))
    print('计算准确率为:', answer.score(x,y,'auc'))

In [ ]:
def Posterior(data, label , ** argv):
    Y = data.iloc[:,-1]
    tagset = set(Y) 
    probs = {} 
    for tag in tagset:
        p = ProbabilityJoin(data, tag, ** argv)
        probs[tag] = p
    pjoin = sum(probs.values()) 
    return {key : probs[key] / pjoin for key in probs}[label]
def ProbabilityJoin(data, label , ** argv):
    Y = data.iloc[:,-1] 
    P = sum(Y == label)/len(Y)
    for attr in argv.keys():
        p = ProbabilityOnY(data, label , attr, argv[attr])
        P *= p
    return P
def ProbabilityOnY(data, label , attr, value):
    Y = data.iloc[:,-1] == label
    A = data[attr] == value
    return sum(Y & A) / sum(Y)

In [ ]:
from numpy import sqrt, pi, exp
def prob(mu, sigma):
    def calprob(val):
        return 1/sqrt(2 * pi * sigma**2)*exp(-(mu-val)**2/(2*sigma**2))
    return calprob
def ProbabilityOnY1(data, label, attr, value):
	Y = data.iloc[:,-1] == label
	X = data[attr][Y]
	mu = np.mean(X)
	sigma = np.std(X)
	return prob(mu, sigma)(value) #prob根据mu, sigma生成概率密度函数
def Posterior1(data, label , ** argv):
    Y = data.iloc[:,-1]
    tagset = set(Y) 
    probs = {} 
    for tag in tagset:
        p = ProbabilityJoin(data, tag, ** argv)
        probs[tag] = p
    pjoin = sum(probs.values()) 
    return {key : probs[key] / pjoin for key in probs}[label]
def ProbabilityJoin(data, label , ** argv):
    Y = data.iloc[:,-1] 
    P = sum(Y == label)/len(Y)
    for attr in argv.keys():
        p = ProbabilityOnY1(data, label , attr, argv[attr])
        P *= p
    return P